### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by cwienberg** [Factual/docker-cdh5-dev#13]
For better or for worse, a lot of docker images at Factual depend on docker-cdh5-dev (or other images in its dependency chain). This causes pain when the image changes and removes a dependency that a downstream image depended on.

I think we should add versioning, that way dependencies don't shift out from under downstream users of this image. We can set it up to still release a `latest` as well for users who just want the most recent updates.

Thoughts @bfs?

CC @kevinfactual @worace @sesquipedaliya

**Comment by worace** [comment]
Yeah this seems helpful. I'm not sure if there are common ways people handle this stuff but seems like we could just put a `VERSION` file in the repo and have a script that reads that to tag the image. Bonus points if it pushes a git tag in the repo for the release.

I'm not sure if there is anything we can do in DockerHub to prevent tags other than latest from being overwritten, so we might just have to try to be careful about doing that. I guess we could include some scripting to check against it before pushing as well.

**Comment by ndigati** [comment]
I think something like this was attempted previously (we have a tag called `java8-20161101`). You should be able to do this with docker hub and a branch or release for the version tags you want, it just requires someone to maintain them and keep them updated.

**Comment by bilow-factual** [comment]
Tagging to the date that the image was built is probably sufficient for this.

**Comment by cwienberg** [comment]
I agree with @bilow-factual. Just something so that you don't end up on a wild goose chase trying to find the dependency that disappeared when you rebuild your docker image.

**Comment by bilow-factual** [comment]
I'm gonna rebuild and push today.

**Comment by bilow-factual** [comment]
OK, pushed a new build tagged as `20180702` and `latest`. I tagged the last version as `20161118`.

**Comment by bilow-factual** [comment]
@ndigati how do we update the `factual/docker-cdh5-dev` image to point to `registry.prod.factual.com:latest`?

**Comment by bilow-factual** [comment]
Yeah, the images are live:https://registry-ui.prod.factual.com/repo/docker-cdh5-dev/tags

But the devbox images etc. depend on `factual/docker-cdh5-dev`, which is in the public docker registry.

**Comment by ndigati** [comment]
Why do you want to move these images to the internal registry?

**Comment by cwienberg** [comment]
@bilow-factual why should we switch these to the internal registry?
@ndigati did you set up automatic tagging on dockerhub?

**Comment by ndigati** [comment]
cdh5-dev is currently set to auto build the master, java7, and java8 branches. I also set it to autobuild all tags.

**Comment by cwienberg** [comment]
Thanks Nick! I'll add a line to the readme encouraging users to tag their changes with a date and close this.
